-- CreateEnum
CREATE TYPE "VAITRO" AS ENUM ('Sinh Vien', 'Giang Vien', 'Quan Tri');

-- CreateEnum
CREATE TYPE "GIOITINH" AS ENUM ('Nam', 'Nu', 'Khac');

-- CreateEnum
CREATE TYPE "HOCVI" AS ENUM ('Cu Nhan', 'Thac Si', 'Tien Si', 'Pho Giao Su', 'Giao Su');

-- CreateTable
CREATE TABLE "TAIKHOAN" (
    "MaTK" SERIAL NOT NULL,
    "TenTK" TEXT NOT NULL,
    "Email" TEXT NOT NULL,
    "MatKhau" TEXT NOT NULL,
    "Ten" TEXT NOT NULL,
    "VaiTro" "VAITRO" NOT NULL,
    "LanDauDangNhap" BOOLEAN NOT NULL,

    CONSTRAINT "TAIKHOAN_pkey" PRIMARY KEY ("MaTK")
);

-- CreateTable
CREATE TABLE "SINHVIEN" (
    "MaSV" SERIAL NOT NULL,
    "NgaySinh" TIMESTAMP(3) NOT NULL,
    "GioiTinh" "GIOITINH" NOT NULL DEFAULT 'Nam',
    "DiaChi" TEXT NOT NULL,
    "SDT" TEXT NOT NULL,
    "MaTK" INTEGER NOT NULL,
    "MaKhoa" INTEGER NOT NULL,
    "MaLopHC" INTEGER NOT NULL,

    CONSTRAINT "SINHVIEN_pkey" PRIMARY KEY ("MaSV")
);

-- CreateTable
CREATE TABLE "KHOA" (
    "MaKhoa" SERIAL NOT NULL,
    "TenKhoa" TEXT NOT NULL,
    "MoTa" TEXT NOT NULL,

    CONSTRAINT "KHOA_pkey" PRIMARY KEY ("MaKhoa")
);

-- CreateTable
CREATE TABLE "LOPHC" (
    "MaLopHC" SERIAL NOT NULL,
    "TenLopHC" TEXT NOT NULL,
    "SoLuong" INTEGER NOT NULL,
    "MaKhoa" INTEGER NOT NULL,
    "MaGV" INTEGER NOT NULL,

    CONSTRAINT "LOPHC_pkey" PRIMARY KEY ("MaLopHC")
);

-- CreateTable
CREATE TABLE "HOCPHAN" (
    "MaHP" SERIAL NOT NULL,
    "TenHP" TEXT NOT NULL,
    "SoTC" INTEGER NOT NULL,
    "SoTiet" INTEGER NOT NULL,
    "HocKy" INTEGER NOT NULL,
    "NamHoc" INTEGER NOT NULL,
    "NgayBatDau" TIMESTAMP(3) NOT NULL,
    "NgayKetThuc" TIMESTAMP(3) NOT NULL,
    "MaGV" INTEGER NOT NULL,

    CONSTRAINT "HOCPHAN_pkey" PRIMARY KEY ("MaHP")
);

-- CreateTable
CREATE TABLE "GIANGVIEN" (
    "MaGV" SERIAL NOT NULL,
    "HocVi" "HOCVI" NOT NULL DEFAULT 'Cu Nhan',
    "ChuyenNganh" TEXT NOT NULL,
    "MaTK" INTEGER NOT NULL,

    CONSTRAINT "GIANGVIEN_pkey" PRIMARY KEY ("MaGV")
);

-- CreateTable
CREATE TABLE "DIEM" (
    "DiemCC" DECIMAL(65,30) NOT NULL,
    "DiemKT1" DECIMAL(65,30) NOT NULL,
    "DiemKT2" DECIMAL(65,30) NOT NULL,
    "DiemTL" DECIMAL(65,30) NOT NULL,
    "DiemThi" DECIMAL(65,30) NOT NULL,
    "MaSV" INTEGER NOT NULL,
    "MaHP" INTEGER NOT NULL,

    CONSTRAINT "DIEM_pkey" PRIMARY KEY ("MaSV","MaHP")
);

-- CreateIndex
CREATE UNIQUE INDEX "TAIKHOAN_TenTK_key" ON "TAIKHOAN"("TenTK");

-- CreateIndex
CREATE UNIQUE INDEX "TAIKHOAN_Email_key" ON "TAIKHOAN"("Email");

-- CreateIndex
CREATE UNIQUE INDEX "SINHVIEN_SDT_key" ON "SINHVIEN"("SDT");

-- AddForeignKey
ALTER TABLE "SINHVIEN" ADD CONSTRAINT "SINHVIEN_MaTK_fkey" FOREIGN KEY ("MaTK") REFERENCES "TAIKHOAN"("MaTK") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SINHVIEN" ADD CONSTRAINT "SINHVIEN_MaKhoa_fkey" FOREIGN KEY ("MaKhoa") REFERENCES "KHOA"("MaKhoa") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SINHVIEN" ADD CONSTRAINT "SINHVIEN_MaLopHC_fkey" FOREIGN KEY ("MaLopHC") REFERENCES "LOPHC"("MaLopHC") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LOPHC" ADD CONSTRAINT "LOPHC_MaKhoa_fkey" FOREIGN KEY ("MaKhoa") REFERENCES "KHOA"("MaKhoa") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LOPHC" ADD CONSTRAINT "LOPHC_MaGV_fkey" FOREIGN KEY ("MaGV") REFERENCES "GIANGVIEN"("MaGV") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HOCPHAN" ADD CONSTRAINT "HOCPHAN_MaGV_fkey" FOREIGN KEY ("MaGV") REFERENCES "GIANGVIEN"("MaGV") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GIANGVIEN" ADD CONSTRAINT "GIANGVIEN_MaTK_fkey" FOREIGN KEY ("MaTK") REFERENCES "TAIKHOAN"("MaTK") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DIEM" ADD CONSTRAINT "DIEM_MaSV_fkey" FOREIGN KEY ("MaSV") REFERENCES "SINHVIEN"("MaSV") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DIEM" ADD CONSTRAINT "DIEM_MaHP_fkey" FOREIGN KEY ("MaHP") REFERENCES "HOCPHAN"("MaHP") ON DELETE RESTRICT ON UPDATE CASCADE;
